#!/usr/bin/env bash
# install web server Nginx
# Redirection
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "30i \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=SK9KEwE6JmE permanent;" /etc/nginx/sites-available/default
sudo service nginx start
