#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt-get update
sudo apt-get install haproxy=2.0.\* -y
echo 104.196.157.169 781-web-01 | sudo tee -a /etc/hosts
echo 34.73.109.46 781-web-02 | sudo tee -a /etc/hosts
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.org
echo -e "\nfrontend http_front\n\tbind *:80\n\tdefault_backend http_back\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\nbackend http_back\n\tbalance roundrobin\n\tserver 781-web-01 104.196.157.169:80 check\n\tserver 781-web-02 34.73.109.46:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
