#!/usr/bin/env bash
#Using your debugging skills, find out whats keeping your Ubuntu containers Nginx installation from listening on port 80
sed -i -e 's/8080/80/g' /etc/nginx/sites-enabled/default, sudo service nginx restart, sudo service nginx quit

