#!/usr/bin/env bash
echo "$!" > "/var/run/holbertonscript.pid"
trap 'echo "I hate the kill command";' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "/var/run/holbertonscript.pid";' SIGQUIT
while :; do echo "To infinity and beyond"; sleep 2 done
