#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
word=1
while [ $word -le 20 ]
do
    echo $word 
    case $word in
        4)
            echo "bad luck from China";;
        9)
            echo "bad luck from Japan";;
        17)
            echo "bad luck from Italy";;
    esac
	    ((word++))
done
